experiment_name: agent-openai-eval-only
trial_name: trial0

seed: 1
tokenizer_path: Qwen/Qwen3-0.6B

workflow: areal.workflow.openai.math_agent.MathAgent
workflow_kwargs:
  temperature: ${gconfig.temperature}
  top_p: ${gconfig.top_p}
  max_completion_tokens: ${gconfig.max_new_tokens}

cluster:
  fileroot: /tmp/areal/experiments
  name_resolve:
    type: nfs
    nfs_record_root: /tmp/areal/name_resolve

allocation_mode: vllm:d1p1t1

scheduler:
  type: local

rollout:
  experiment_name: ${experiment_name}
  trial_name: ${trial_name}
  fileroot: ${cluster.fileroot}
  tokenizer_path: ${tokenizer_path}
  max_concurrent_rollouts: 16
  consumer_batch_size: ${valid_dataset.batch_size}
  max_head_offpolicyness: 1000000000000
  dump_to_file: true
  scheduling_spec:
    - task_type: worker
      port_count: 2
      gpu: 1
      mem: 32
      cmd: python -m areal.infra.rpc.rpc_server
      env_vars: {}
  openai:
    mode: inline
    export_style: individual

gconfig:
  n_samples: 2
  min_new_tokens: 0
  max_new_tokens: 512
  max_tokens: 1024
  greedy: false
  top_p: 1.0
  temperature: 0.6

vllm:
  model: ${tokenizer_path}
  seed: ${seed}
  skip_tokenizer_init: false
  dtype: auto
  max_model_len: ${gconfig.max_tokens}
  gpu_memory_utilization: 0.4

valid_dataset:
  batch_size: 1
  shuffle: false
  pin_memory: true
  num_workers: 4
  drop_last: false
  path: openai/gsm8k
  type: rl
